kind: ServiceAccount
apiVersion: v1
metadata:
  name: streamsets-agent
  labels:
    app.kubernetes.io/name: streamsets-agent
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: streamsets-agent
  labels:
    app.kubernetes.io/name: streamsets-agent
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","get", "update"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streamsets-agent
  labels:
    app.kubernetes.io/name: streamsets-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: streamsets-agent
subjects:
  - kind: ServiceAccount
    name: streamsets-agent
---
